DROP TABLE IF EXISTS product CASCADE;
DROP TABLE IF EXISTS orders CASCADE;

CREATE TABLE product (id SERIAL PRIMARY KEY, name VARCHAR(255) NOT NULL, img_name VARCHAR(255) NOT NULL, category VARCHAR(255) NOT NULL, quantity INTEGER NOT NULL, price INTEGER NOT NULL, sold_out BOOLEAN NOT NULL);

CREATE TABLE orders (id SERIAL PRIMARY KEY, first_name VARCHAR(255) NOT NULL, last_name VARCHAR(255) NOT NULL, order_list VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, city VARCHAR(255) NOT NULL);