DROP TABLE IF EXISTS product CASCADE;

CREATE TABLE product (id SERIAL PRIMARY KEY, name VARCHAR(255) NOT NULL, img_name VARCHAR(255) NOT NULL, category VARCHAR(255) NOT NULL, quantity INTEGER NOT NULL, price INTEGER NOT NULL, sold_out BOOLEAN NOT NULL);